apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: ndbs.ndbcontroller.mysql.com
spec:
  group: ndbcontroller.mysql.com
  version: v1alpha1
  names:
    kind: Ndb
    plural: ndbs
  scope: Namespaced
  subresources:
    status: {}
