apiVersion: v1
kind: Service
metadata:
  name: example-ndb-mgmd-0
  labels: 
    ndbcontroller.mysql.com/v1alpha1: example-ndb
spec:
  publishNotReadyAddresses: true
  selector:
    #statefulset.kubernetes.io/pod-name: example-ndb-mgmd-0
    ndbcontroller.mysql.com/nodetype: mgmd
    ndbcontroller.mysql.com/v1alpha1: example-ndb
  ports:
    - protocol: TCP
      name: agent
      port: 8080
      targetPort: 8080
  type: LoadBalancer
